### ISSUE TITLE
Allow additional fields in `clorinde.toml` to be copied to `Cargo.toml`

### ISSUE THREAD

**Issue by TimDiekmann** [halcyonnouveau/clorinde#108]
`clorinde.toml` covers some fields from `[package]` which is great. It already has basic workspace support, which is also amazing. However, there is a gap: many fields allow a `workspace = true`, e.g. this is a very valid `Cargo.toml`:

```toml
[package]
name              = "..."
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
authors.workspace = true
description       = "..."
```

Further, it would be great, if it would be possible to also allow passing `[lints]` as section. 
In my case, I disabled three lints in `clorinde/Cargo.toml`:
```toml
[lints.rust]
dead_code = "allow"
exported_private_dependencies = "allow" # Only interesting if the public-dependencies feature is enabled
unused_imports = "allow"
```
to silence all linting warnings for me.

As an alternative to the lint section you could also ignore the lints in the generated code or fix them, however, for the public dependency thing it would require to set the dependencies to `public = true`.
To work around this, I simply appended the lints to the `Cargo.toml` as part of the codegen step, but a proper upstream solution would be amazing.
