### ISSUE TITLE
I have issues around custom `tstzrange` (and possibly other unsupported types)

### ISSUE THREAD

**Issue by TimDiekmann** [halcyonnouveau/clorinde#112]
I encountered an issue with the following query:
```sql
--! insert_temporal_metadata
INSERT INTO temporal_metadata (
    transaction_time
) VALUES (
    :transaction_time
);
```

`transaction_time` is of type `TSTZRANGE`, which is not supported directly. So I tried to add a type mapping as shown in the documentation:
```toml
[types.crates]
postgres_range = { version = "0.11.1", features = ["with-chrono-0_4"] }

[types.mapping]
"pg_catalog.tstzrange" = "postgres_range::Range<chrono::DateTime<chrono::FixedOffset>>"
```

However, running the codegen does fail with the following error:
```text
Error:   × Couldn't register SQL type.
   ╭─[queries/test.sql:1:5]
 1 │ --! insert_temporal_metadata
   ·     ────────────────┬────────────────
   ·                     ╰── this query contains an unsupported type (name: postgres_range::Range<chrono::DateTime<chrono::FixedOffset>>, type: tstzrange)
 2 │ INSERT INTO temporal_metadata (
   ╰────
```

Am I overseeing something or was there a regression that the showcased code does not work anymore? Happy to provide more context if required.
