### ISSUE TITLE
Bug: the name `time` is defined multiple times

### ISSUE THREAD

**Issue by jacobsvante** [halcyonnouveau/clorinde#41]
At least clorinde 0.11.1 and 0.11.2 generated this error:

```rust
error[E0428]: the name `time` is defined multiple times
  --> clorinde/src/types.rs:11:1
   |
4  | pub mod time {
   | ------------ previous definition of the module `time` here
...
11 | pub mod time {
   | ^^^^^^^^^^^^ `time` redefined here
   |
   = note: `time` must be defined only once in the type namespace of this module
```

This is what's generated for me:
```rust
#[cfg(feature = "chrono")]
pub mod time {
    pub type Timestamp = chrono::NaiveDateTime;
    pub type TimestampTz = chrono::DateTime<chrono::FixedOffset>;
    pub type Date = chrono::NaiveDate;
    pub type Time = chrono::NaiveTime;
}
#[cfg(feature = "time")]
pub mod time {
    pub type Timestamp = time::PrimitiveDateTime;
    pub type TimestampTz = time::OffsetDateTime;
    pub type Date = time::Date;
    pub type Time = time::Time;
}
```

Sorry for not including more details, I'm in a bit of a hurry...

**Comment by Defelo** [comment]
As a workaround one could just default to chrono if both features are enabled:

```rust
#[cfg(feature = "chrono")]
pub mod time {
    // ...
}
#[cfg(all(feature = "time", not(feature = "chrono")))]
pub mod time {
    // ...
}
```

**Comment by beanpuppy** [comment]
@Defelo Yeah I think something along those lines would work. But I assume what happened here is @jacobsvante set the `time` feature flag without also setting `default-features = false` which would unset `chrono`. In that case, I think we would set `time` as the default, since the user specifically requested it.

```rust
#[cfg(all(feature = "chrono", not(feature="time")))]
pub mod time {
    // ...
}
#[cfg(feature = "time")]
pub mod time {
    // ...
}
```

**Comment by Defelo** [comment]
Right, that makes sense. Didn't notice that `chrono` is a default feature

**Comment by jacobsvante** [comment]
I actually set default-features=false. Let me get back to you when I've had time to look at it thoroughly.

**Comment by Alt-iOS** [comment]
Also to add to that, the auto-generated cargo.toml doesnt include neither chrono nor time, thus if any of those features is enabled, you cant actually run the code as of 0.13.1
```toml
# This file was generated with `clorinde`. Do not modify.
[package]
name = "db_gen"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["deadpool"]
deadpool = ["dep:deadpool-postgres", "tokio-postgres/default"]
wasm-async = ["tokio-postgres/js"]

chrono = []
time = []

[dependencies]
## Core dependencies
# Postgres types
postgres-types = { version = "0.2.9", features = ["derive"] }
# Postgres interaction
postgres-protocol = "0.6.8"
# Iterator utils required for working with `postgres_protocol::types::ArrayValues`
fallible-iterator = "0.2.0"

## Async client dependencies
# Postgres async client
tokio-postgres = { version = "0.7.13", features = [] }
# Async utils
futures = "0.3.31"

## Async features dependencies
# Async connection pooling
deadpool-postgres = { version = "0.14.1", optional = true }
```
