### ISSUE TITLE
Support range types

### ISSUE THREAD

**Issue by Alt-iOS** [halcyonnouveau/clorinde#43]
when generating a query that returns a tstzrange I get the following error, but tokio-postgres does [support it](https://prisma.github.io/prisma-engines/doc/src/postgres_types/type_gen.rs.html#1332)
```
Error:
  × Couldn't register SQL type.
   ╭─[queries/users.sql:1:5]
 1 │ --! insert_user
   ·     ─────┬─────
   ·          ╰── this query contains an unsupported type (name: sys_period, type: tstzrange)
 2 │ INSERT INTO users (name, password_hash) VALUES ( $1, $2 )RETURNING *;
```

**Comment by Alt-iOS** [comment]
If you guys could point me out more or less whats needed to add support I am happy to add a PR

**Comment by beanpuppy** [comment]
I just had a quick look at this and while `rust-postgres` does provide a type for `tstzrange`, it doesn't seem to provide the `ToSql` or `FromSql` traits that we need. However, I've found this crate from the `rust-postgres` author that does add those traits for `chrono` - https://github.com/sfackler/rust-postgres-range. But I'm not sure if adding this dependency to Clorinde is currently something we want to support - something to discuss with @jacobsvante later. 

But in any case, it's possible for you to add it to your project by using custom type settings and adding this to `clorinde.toml`:

```toml
[types.crates]
postgres_range = { version = "0.11.1", features = ["with-chrono-0_4"] }

[types.mapping]
"pg_catalog.tstzrange" = "postgres_range::Range<chrono::DateTime<chrono::FixedOffset>>"
```
