### ISSUE TITLE
Added dependency for derived trait not working

### ISSUE THREAD

**Issue by Folyd** [halcyonnouveau/clorinde#60]
```log
error[E0433]: failed to resolve: use of undeclared crate or module `utoipa`
  --> db/src/queries/product.rs:49:53
   |
49 | #[derive(serde::Serialize, Debug, Clone, PartialEq, utoipa::ToSchema)]
   |                                                     ^^^^^^ use of undeclared crate or module `utoipa`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `db` (lib) due to 1 previous error
```

I already add dependencies to the `build.rs`.
```rs
use std::collections::HashMap;
use std::env;
use std::path::PathBuf;

use clorinde::config::{Config, Package};
use clorinde::config::{CrateDependency, Types};
use dotenv::dotenv;
use postgres::Client;
use postgres::NoTls;

fn main() {
    dotenv().ok();

    let dependencies = [("utoipa".into(), CrateDependency::Simple("5.3".into()))]
        .into_iter()
        .collect();
    let cfg = Config {
        r#async: true,
        serialize: true,
        queries: PathBuf::from("queries"),
        destination: PathBuf::from("db"),
        package: Package {
            name: "db".into(),
            ..Default::default()
        },
        types: Types {
            crate_info: dependencies,
            mapping: HashMap::new(),
            derive_traits: vec![],
        },
        ..Default::default()
    };
    let url = env::var("DATABASE_URL").expect("DATABASE_URL must be set");
    let mut client = Client::connect(&url, NoTls).unwrap();
    clorinde::gen_live(&mut client, cfg).unwrap();
}

```

```sql
--: Product(description?) : utoipa::ToSchema

--! get_by_id : Product
SELECT
    *
FROM
    products
WHERE
    id = :id
    AND is_active = TRUE;
```

The generated code derived `utoipa::ToSchema`.

```rs
#[derive(serde::Serialize, Debug, Clone, PartialEq, utoipa::ToSchema)]
pub struct Product {
    pub id: i32,
    pub description: Option<String>,
    // ...
}
```

However, the generated `Cargo.toml` missing the `utoipa` crate.
```toml
# This file was generated with `clorinde`. Do not modify.
[package]
name = "db"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["deadpool", "chrono"]
deadpool = ["dep:deadpool-postgres", "tokio-postgres/default"]
wasm-async = ["tokio-postgres/js", "chrono?/wasmbind", "time?/wasm-bindgen"]

chrono = ["dep:chrono"]
time = ["dep:time"]

[dependencies]
## Core dependencies
# Postgres types
postgres-types = { version = "0.2.9", features = ["derive"] }
# Postgres interaction
postgres-protocol = "0.6.8"
# Iterator utils required for working with `postgres_protocol::types::ArrayValues`
fallible-iterator = "0.2.0"

## Types dependencies
# TIME, DATE, TIMESTAMP or TIMESTAMPZ
chrono = { version = "0.4.39", optional = true }
time = { version = "0.3.37", optional = true }
# JSON or JSONB
serde_json = { version = "1.0.134", features = ["raw_value"] }
serde = { version = "1.0.217", features = ["derive"] }

## Async client dependencies
# Postgres async client
tokio-postgres = { version = "0.7.13", features = ["with-chrono-0_4", "with-time-0_3", "with-serde_json-1"] }
# Async utils
futures = "0.3.31"

## Async features dependencies
# Async connection pooling
deadpool-postgres = { version = "0.14.1", optional = true }
```
